apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fossology-repo
  namespace: fossology
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
