apiVersion: v1
kind: Service
metadata:
  name: fossology-db
  namespace: fossology
spec:
  clusterIP: None
  selector:
    app: fossology-db
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
