images:
  web:
    pullPolicy: IfNotPresent
  worker:
    pullPolicy: IfNotPresent

repoPersistence:
  accessModes:
    - ReadWriteMany
  storageClassName: shared-rwx

web:
  replicas: 2
  service:
    type: ClusterIP
    port: 80
    targetPort: 80

workers:
  replicas: 4

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: fossology.example.com
      paths:
        - path: /
          pathType: Prefix
