apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fossology
  namespace: argocd
spec:
  description: FOSSology Kubernetes PoC project
  sourceRepos:
    - "*"
  destinations:
    - namespace: fossology
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
