{{- if not .Values.repoPersistence.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fossology.repoPvcName" . }}
  labels:
{{ include "fossology.labels" . | indent 4 }}
spec:
  accessModes:
{{ toYaml .Values.repoPersistence.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.repoPersistence.size }}
{{- with .Values.repoPersistence.storageClassName }}
  storageClassName: {{ . }}
{{- end }}
{{- end }}
