{{- if and .Values.database.internal.enabled .Values.database.internal.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fossology.postgresPvcName" . }}
  labels:
{{ include "fossology.labels" . | indent 4 }}
spec:
  accessModes:
{{ toYaml .Values.database.internal.persistence.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.database.internal.persistence.size }}
{{- with .Values.database.internal.persistence.storageClassName }}
  storageClassName: {{ . }}
{{- end }}
{{- end }}
