{{- if not .Values.database.dbConfSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fossology.dbConfSecretName" . }}
  labels:
{{ include "fossology.labels" . | indent 4 }}
type: Opaque
stringData:
  Db.conf: |
    dbname={{ .Values.database.name }};
    host={{ include "fossology.dbHost" . }};
    user={{ .Values.database.user }};
    password={{ .Values.database.password }};
{{- end }}
