apiVersion: v1
kind: Service
metadata:
  name: {{ include "fossology.fullname" . }}-web
  labels:
{{ include "fossology.labels" . | indent 4 }}
    app: {{ include "fossology.fullname" . }}-web
spec:
  selector:
    app: {{ include "fossology.fullname" . }}-web
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      protocol: TCP
      name: http
{{- if eq .Values.web.service.type "NodePort" }}
      nodePort: {{ .Values.web.service.nodePort }}
{{- end }}
  type: {{ .Values.web.service.type }}
