{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fossology.serviceAccountName" . }}
  labels:
{{ include "fossology.labels" . | indent 4 }}
    app: {{ include "fossology.fullname" . }}-web
{{- end }}
