apiVersion: v1
kind: Service
metadata:
  name: {{ include "fossology.fullname" . }}-workers
  labels:
{{ include "fossology.labels" . | indent 4 }}
    app: {{ include "fossology.fullname" . }}-workers
spec:
  selector:
    app: {{ include "fossology.fullname" . }}-worker
  clusterIP: None
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
